# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(20, 5))
# A = np.random.randint(0, 100, size=(200, 50))
A

array([[38, 38, 92, 46, 78],
       [64,  4,  0, 84, 28],
       [19, 51, 42, 44, 85],
       [51,  8, 25, 45, 65],
       [ 8, 15, 60, 50, 42],
       [21, 13, 17, 83, 55],
       [28, 38, 34, 48, 16],
       [71, 22, 51, 83,  4],
       [17, 94, 18, 16, 26],
       [26, 13, 22, 26, 35],
       [18, 88, 45,  5, 71],
       [71, 21, 67, 86, 69],
       [48, 71, 18, 72, 37],
       [52, 90,  4,  6, 55],
       [56, 82, 14, 48, 78],
       [99, 57, 66, 48,  5],
       [78, 93, 10, 32, 63],
       [51, 80, 48, 78, 78],
       [97, 49, 31, 20, 64],
       [65,  0, 54, 30, 42]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

In [30]:
A.T[np.random.choice(A.T.shape[0], size=A.T.shape[0], replace=False)].T

array([[22, 16, 63, 12, 47],
       [91, 20, 47, 17, 24],
       [58, 49, 91, 96, 67],
       [ 3, 46, 71, 92, 40],
       [77, 34, 63, 46, 60],
       [38, 53, 74, 42, 63],
       [88, 33, 48, 51, 65],
       [89, 32, 95,  2, 47],
       [67, 49, 92, 25,  1],
       [11, 94, 96, 75, 84],
       [98, 89, 84, 58, 86],
       [93, 61, 31, 38, 77],
       [76, 12, 36, 61,  8],
       [52, 51, 70,  9, 81],
       [59, 37, 86, 92, 48],
       [34, 59, 42, 33, 73],
       [27,  8, 82, 73, 74],
       [67, 99, 81, 95, 29],
       [62, 66, 75, 45, 31],
       [79,  3, 43, 85,  1]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

In [53]:
A[np.sum(A[:, 0::2], axis=1) > np.mean(np.sum(A[:, 1::2], axis=1))]

array([[24, 17, 20, 47, 91],
       [67, 96, 49, 91, 58],
       [60, 46, 34, 63, 77],
       [63, 42, 53, 74, 38],
       [65, 51, 33, 48, 88],
       [47,  2, 32, 95, 89],
       [84, 75, 94, 96, 11],
       [86, 58, 89, 84, 98],
       [77, 38, 61, 31, 93],
       [81,  9, 51, 70, 52],
       [48, 92, 37, 86, 59],
       [73, 33, 59, 42, 34],
       [29, 95, 99, 81, 67],
       [31, 45, 66, 75, 62]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [57]:
np.argmax(np.max(A, axis=1) - np.min(A, axis=1))

7

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [73]:
arr_new = A.reshape(1,-1)
arr_new = arr_new.argsort().argsort() + 1
arr_new.reshape(A.shape)

array([[ 38,  10,  12,  59,  15],
       [ 16,  13,  14,  39,  89],
       [ 63,  97,  44,  88,  50],
       [ 31,  90,  37,  66,   5],
       [ 53,  36,  25,  57,  75],
       [ 58,  32,  48,  70,  29],
       [ 60,  46,  24,  41,  85],
       [ 40,   3,  22,  95,  87],
       [  1,  17,  43,  91,  64],
       [ 80,  71,  94,  98,   9],
       [ 83,  49,  86,  81,  99],
       [ 74,  30,  55,  21,  93],
       [  6,  54,  11,  27,  73],
       [ 77,   8,  45,  65,  47],
       [ 42,  92,  28,  84,  52],
       [ 67,  23,  51,  33,  26],
       [ 69,  68,   7,  79,  18],
       [ 19,  96, 100,  78,  62],
       [ 20,  35,  61,  72,  56],
       [  2,  82,   4,  34,  76]], dtype=int64)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [83]:
min_arr = A.min(axis=1).reshape((-1,1))
max_arr = A.max(axis=1).reshape((-1,1))
(A - min_arr)/(max_arr - min_arr)

array([[0.68627451, 0.        , 0.07843137, 1.        , 0.19607843],
       [0.09459459, 0.        , 0.04054054, 0.40540541, 1.        ],
       [0.38297872, 1.        , 0.        , 0.89361702, 0.19148936],
       [0.41573034, 1.        , 0.48314607, 0.76404494, 0.        ],
       [0.60465116, 0.27906977, 0.        , 0.6744186 , 1.        ],
       [0.69444444, 0.11111111, 0.41666667, 1.        , 0.        ],
       [0.58181818, 0.32727273, 0.        , 0.27272727, 1.        ],
       [0.48387097, 0.        , 0.32258065, 1.        , 0.93548387],
       [0.        , 0.26373626, 0.52747253, 1.        , 0.72527473],
       [0.85882353, 0.75294118, 0.97647059, 1.        , 0.        ],
       [0.7       , 0.        , 0.775     , 0.65      , 1.        ],
       [0.74193548, 0.11290323, 0.48387097, 0.        , 1.        ],
       [0.        , 0.77941176, 0.05882353, 0.41176471, 1.        ],
       [1.        , 0.        , 0.58333333, 0.84722222, 0.59722222],
       [0.2       , 1.        , 0.

# Задание 2.6 (2 балла)

Сгенерируйте новый трехмерный массив, размерности $10 \times 200 \times 50$. Подмассивы по нулевой оси должны состоять из элементов `A`, умноженных на $1 - 10$ соответственно

In [99]:
(A.reshape((-1, *A.shape)) * np.arange(1, 11).reshape((-1, 1, 1)))

array([[[ 47,  12,  16,  63,  22],
        [ 24,  17,  20,  47,  91],
        [ 67,  96,  49,  91,  58],
        [ 40,  92,  46,  71,   3],
        [ 60,  46,  34,  63,  77],
        [ 63,  42,  53,  74,  38],
        [ 65,  51,  33,  48,  88],
        [ 47,   2,  32,  95,  89],
        [  1,  25,  49,  92,  67],
        [ 84,  75,  94,  96,  11],
        [ 86,  58,  89,  84,  98],
        [ 77,  38,  61,  31,  93],
        [  8,  61,  12,  36,  76],
        [ 81,   9,  51,  70,  52],
        [ 48,  92,  37,  86,  59],
        [ 73,  33,  59,  42,  34],
        [ 74,  73,   8,  82,  27],
        [ 29,  95,  99,  81,  67],
        [ 31,  45,  66,  75,  62],
        [  1,  85,   3,  43,  79]],

       [[ 94,  24,  32, 126,  44],
        [ 48,  34,  40,  94, 182],
        [134, 192,  98, 182, 116],
        [ 80, 184,  92, 142,   6],
        [120,  92,  68, 126, 154],
        [126,  84, 106, 148,  76],
        [130, 102,  66,  96, 176],
        [ 94,   4,  64, 190, 178],
        [  2,  50,

# Задание 2.7 (2 балла)

Создайте новый массив, такой же размерности, как и `A`, в котором сначала сгруппированы четные столбцы `A`, потом  нечетные. Используйте [np.concat()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) 

In [6]:
np.concatenate((A[:, 0::2], A[:, 1::2]), axis=1)

array([[53, 58,  1, 57, 37],
       [81, 91, 26, 69, 95],
       [70, 64, 30,  9, 30],
       [84, 17, 91, 57,  4],
       [20,  1, 79, 46, 86],
       [61, 75, 69, 41, 43],
       [11, 58, 43,  0, 49],
       [37, 96, 31, 16, 43],
       [62, 44, 32,  7, 86],
       [52,  1, 57, 60, 51],
       [25, 57, 84, 40, 55],
       [29, 45, 79, 85, 74],
       [40, 99, 74, 43, 60],
       [28, 98, 96, 32, 85],
       [ 3, 39, 24, 20, 35],
       [72, 26, 25, 75, 84],
       [46, 17, 71, 25,  4],
       [22, 94, 89, 36, 36],
       [75, 84, 71, 31, 90],
       [38, 51, 96, 13, 96]])

# Задание 2.8 (2 балла)

Посчитайте количество строк массива `A`, в который все элементы больше 5. Используйте [np.all()](https://numpy.org/doc/stable/reference/generated/numpy.all.html) 

In [10]:
np.sum(np.all((A > 5), axis=1))

13

# Задание 2.9 (2 балла)

Поделите массив `A` горизонтально на 10 частей и создайте новый массив размерности $20 \times 50$, который является средним этих частей. Используйте [np.split()](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [13]:
np.mean(np.split(A, 10), axis=0)

array([[40.5, 27.8, 52.1, 53.2, 50.9],
       [50.4, 48.4, 59.4, 61.1, 65.9]])

# Задание 2.10 (4 балла)

"Разверните" массив `A` в одномерный массив. Оставьте в нём только уникальные элементы в том же порядке, в котором они встречаются в массиве. Используйте [np.unique()](https://numpy.org/doc/stable/reference/generated/numpy.unique.html)

In [59]:
B = A.reshape((-1))
B

array([53, 57, 58, 37,  1, 81, 69, 91, 95, 26, 70,  9, 64, 30, 30, 84, 57,
       17,  4, 91, 20, 46,  1, 86, 79, 61, 41, 75, 43, 69, 11,  0, 58, 49,
       43, 37, 16, 96, 43, 31, 62,  7, 44, 86, 32, 52, 60,  1, 51, 57, 25,
       40, 57, 55, 84, 29, 85, 45, 74, 79, 40, 43, 99, 60, 74, 28, 32, 98,
       85, 96,  3, 20, 39, 35, 24, 72, 75, 26, 84, 25, 46, 25, 17,  4, 71,
       22, 36, 94, 36, 89, 75, 31, 84, 90, 71, 38, 13, 51, 96, 96])

In [61]:
unique, indices = np.unique(B, return_inverse=True)
unique, indices

(array([ 0,  1,  3,  4,  7,  9, 11, 13, 16, 17, 20, 22, 24, 25, 26, 28, 29,
        30, 31, 32, 35, 36, 37, 38, 39, 40, 41, 43, 44, 45, 46, 49, 51, 52,
        53, 55, 57, 58, 60, 61, 62, 64, 69, 70, 71, 72, 74, 75, 79, 81, 84,
        85, 86, 89, 90, 91, 94, 95, 96, 98, 99]),
 array([34, 36, 37, 22,  1, 49, 42, 55, 57, 14, 43,  5, 41, 17, 17, 50, 36,
         9,  3, 55, 10, 30,  1, 52, 48, 39, 26, 47, 27, 42,  6,  0, 37, 31,
        27, 22,  8, 58, 27, 18, 40,  4, 28, 52, 19, 33, 38,  1, 32, 36, 13,
        25, 36, 35, 50, 16, 51, 29, 46, 48, 25, 27, 60, 38, 46, 15, 19, 59,
        51, 58,  2, 10, 24, 20, 12, 45, 47, 14, 50, 13, 30, 13,  9,  3, 44,
        11, 21, 56, 21, 53, 47, 18, 50, 54, 44, 23,  7, 32, 58, 58],
       dtype=int64))

In [52]:
unique[indices]

array([53, 57, 58, 37,  1, 81, 69, 91, 95, 26, 70,  9, 64, 30, 30, 84, 57,
       17,  4, 91, 20, 46,  1, 86, 79, 61, 41, 75, 43, 69, 11,  0, 58, 49,
       43, 37, 16, 96, 43, 31, 62,  7, 44, 86, 32, 52, 60,  1, 51, 57, 25,
       40, 57, 55, 84, 29, 85, 45, 74, 79, 40, 43, 99, 60, 74, 28, 32, 98,
       85, 96,  3, 20, 39, 35, 24, 72, 75, 26, 84, 25, 46, 25, 17,  4, 71,
       22, 36, 94, 36, 89, 75, 31, 84, 90, 71, 38, 13, 51, 96, 96])

In [58]:
u, i = np.unique(indices, return_inverse=True)
u, i

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int64),
 array([34, 36, 37, 22,  1, 49, 42, 55, 57, 14, 43,  5, 41, 17, 17, 50, 36,
         9,  3, 55, 10, 30,  1, 52, 48, 39, 26, 47, 27, 42,  6,  0, 37, 31,
        27, 22,  8, 58, 27, 18, 40,  4, 28, 52, 19, 33, 38,  1, 32, 36, 13,
        25, 36, 35, 50, 16, 51, 29, 46, 48, 25, 27, 60, 38, 46, 15, 19, 59,
        51, 58,  2, 10, 24, 20, 12, 45, 47, 14, 50, 13, 30, 13,  9,  3, 44,
        11, 21, 56, 21, 53, 47, 18, 50, 54, 44, 23,  7, 32, 58, 58],
       dtype=int64))

array([34, 36, 37, 22,  1, 49, 42, 55, 57, 14, 43,  5, 41, 17, 17, 50, 36,
        9,  3, 55, 10, 30,  1, 52, 48, 39, 26, 47, 27, 42,  6,  0, 37, 31,
       27, 22,  8, 58, 27, 18, 40,  4, 28, 52, 19, 33, 38,  1, 32, 36, 13,
       25, 36, 35, 50, 16, 51, 29, 46, 48, 25, 27, 60, 38, 46, 15, 19, 59,
       51, 58,  2, 10, 24, 20, 12, 45, 47, 14, 50, 13, 30, 13,  9,  3, 44,
       11, 21, 56, 21, 53, 47, 18, 50, 54, 44, 23,  7, 32, 58, 58],
      dtype=int64)

# Задание 2.11 (3 балла)

Создайте одномерный массив размерности $200$, в котором каждый элемент - евклидово расстояние между соответствующей строкой `A` и "средней" строкой `A`

In [68]:
mean_row = np.mean(A, axis=0)
np.sqrt(np.sum((A - mean_row) ** 2, axis=1))

array([64.18767405, 77.09447127, 55.32863183, 85.04444426, 70.45819683,
       30.55090015, 54.28680779, 55.95406598, 53.93011682, 59.6645414 ,
       32.91439655, 57.39388034, 46.64501581, 65.69746951, 63.9074135 ,
       69.19579106, 68.24336964, 58.31858623, 54.40181523, 60.25908645])

# Задание 2.12 (2 балла)

Создайте новый массив, который состоит из элементов `A`, измененных по следующим правилам:
- если элемент меньше $50$, то он умножается на $2$
- в противном случае он умножается на $3$

Используйте [np.where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html)

In [69]:
np.where(A < 50, A * 2, A * 3)

array([[159, 171, 174,  74,   2],
       [243, 207, 273, 285,  52],
       [210,  18, 192,  60,  60],
       [252, 171,  34,   8, 273],
       [ 40,  92,   2, 258, 237],
       [183,  82, 225,  86, 207],
       [ 22,   0, 174,  98,  86],
       [ 74,  32, 288,  86,  62],
       [186,  14,  88, 258,  64],
       [156, 180,   2, 153, 171],
       [ 50,  80, 171, 165, 252],
       [ 58, 255,  90, 222, 237],
       [ 80,  86, 297, 180, 222],
       [ 56,  64, 294, 255, 288],
       [  6,  40,  78,  70,  48],
       [216, 225,  52, 252,  50],
       [ 92,  50,  34,   8, 213],
       [ 44,  72, 282,  72, 267],
       [225,  62, 252, 270, 213],
       [ 76,  26, 153, 288, 288]])

# Задание 2.13 (7 баллов)

Разверните массив `A` в одномерный массив. Создайте три новых массива, подсчитав скользящие средние по окнам $3$, $5$, $10$. Найдите сумму этих массивов, выровнив из размерности нулями справа

*Tip: реализуйте функцию, которая считает скользящее среднее. Используйте [np.cumsum()](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html) или [np.convolve()](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html)*

In [27]:
A.reshape((-1, )).copy()

array([38, 38, 92, 46, 78, 64,  4,  0, 84, 28, 19, 51, 42, 44, 85, 51,  8,
       25, 45, 65,  8, 15, 60, 50, 42, 21, 13, 17, 83, 55, 28, 38, 34, 48,
       16, 71, 22, 51, 83,  4, 17, 94, 18, 16, 26, 26, 13, 22, 26, 35, 18,
       88, 45,  5, 71, 71, 21, 67, 86, 69, 48, 71, 18, 72, 37, 52, 90,  4,
        6, 55, 56, 82, 14, 48, 78, 99, 57, 66, 48,  5, 78, 93, 10, 32, 63,
       51, 80, 48, 78, 78, 97, 49, 31, 20, 64, 65,  0, 54, 30, 42])

In [29]:
D = A.reshape((-1, )).copy()

In [30]:
np.convolve(D, np.ones(3), mode="same")[1:-1]

array([168., 176., 216., 188., 146.,  68.,  88., 112., 131.,  98., 112.,
       137., 171., 180., 144.,  84.,  78., 135., 118.,  88.,  83., 125.,
       152., 113.,  76.,  51., 113., 155., 166., 121., 100., 120.,  98.,
       135., 109., 144., 156., 138., 104., 115., 129., 128.,  60.,  68.,
        65.,  61.,  61.,  83.,  79., 141., 151., 138., 121., 147., 163.,
       159., 174., 222., 203., 188., 137., 161., 127., 161., 179., 146.,
       100.,  65., 117., 193., 152., 144., 140., 225., 234., 222., 171.,
       119., 131., 176., 181., 135., 105., 146., 194., 179., 206., 204.,
       253., 224., 177., 100., 115., 149., 129., 119.,  84., 126.])

In [ ]:
np.convolve(D, np.ones(5), mode="same")[2:-2]

In [ ]:
np.convolve(D, np.ones(10), mode="same")[5:-4]

# Задание 2.14 (8 баллов)

Постройте график функции $$f(x) = (5  \sin(2x) - \cos^2(x) - 1 + |x^3| - x^2) / (x^2 + 1)$$  

и производной от этой функции.  Найдите минимум с помощью `scipy` и обозначьте его на графике. На этой же оси постройте графики скользящего среднего этой функции с окном $1$, $2$, $5$.

# Задание 2.15 (10 баллов)

Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [2]:
from typing import List 

def sample(x: List[int], c: int) -> List[int]:
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)   

[0, 4, 4, 0, 0]

Реализуйте данный алгоритм более оптимальным способом на массивах `numpy`, без использования циклов. Проверьте корректность и идентичность алгоритмов семплирования с помощью статистических тестов.

# Задание 2.16 (5 баллов)

Есть следующий алгоритм "случайного блуждания"

In [3]:
import random 

def walk(n: int):
    cur_position = 0
    for i in range(n):
        cur_position += random.choice([-3, -1, 0, 2, 3])

    return cur_position

walk(10_000)

2003

Реализуйте более эффективную версию с помощью `numpy`, сравните производительность (используя, например, magic `timeit`). Воспользовавшись [kdeplot()](https://seaborn.pydata.org/generated/seaborn.kdeplot.html) или аналогами, постройте график распределения значений `walk(10_000)` на каком-то разумном числе запусков. 

# Задание 2.17 (5 баллов)

Имеется функция, которая проделывает достаточно странные манипуляции с массивом `numpy`

In [4]:
import numpy.typing as npt

def strange_conv(a: npt.NDArray[np.float64]) -> np.float64:
    x = a.shape[0]
    y = a.shape[1]

    t = 1.
    for y in range(y - 5):
        for x in range(x - 3):
            c = 1.5 * a[y+1, x+2] - a[y+5, x+3] * a[y, x] + 0.2 * a[y+4, x]
            t = 0.2 * t + 0.8 * c

    return t


a = np.random.random((10000, 10000))
strange_conv(a)


-0.13580565475012618

Оптимизируйте данную функцию с помощью (2 на выбор):
- [Numba](https://numba.pydata.org)
- `Cython` (+5 баллов)
- [Taichi](https://github.com/taichi-dev/taichi) (+5 баллов)
- `Pythran `[[1]](https://pythran.readthedocs.io/en/latest/), [[2]](https://serge-sans-paille.github.io/pythran-stories/pythran-tutorial.html) (+2 балла)

Сравните производительность.